# Generated by Django 2.1.2 on 2019-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.CharField(max_length=50)),
                ('fish', models.CharField(max_length=50)),
                ('quantiy', models.IntegerField()),
            ],
        ),
    ]
