# Generated by Django 2.2.2 on 2019-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
