# Generated by Django 2.2.2 on 2019-08-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20190618_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('farm_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer'),
        ),
    ]
